// apps/api/src/database/seeding/factories/countries.factory.ts

import { CountryEntity } from '../../entities/country.entity';
import { CountryRegion } from '@connect-phone/shared-types';

//-----------------------------------------------------------------------------

const countriesData: Record<string, { name: string; region: CountryRegion }> = {
  ad: { name: 'Andorra', region: CountryRegion.EUROPE },
  ae: { name: 'United Arab Emirates', region: CountryRegion.ASIA },
  af: { name: 'Afghanistan', region: CountryRegion.ASIA },
  ag: { name: 'Antigua and Barbuda', region: CountryRegion.AMERICA },
  ai: { name: 'Anguilla', region: CountryRegion.AMERICA },
  al: { name: 'Albania', region: CountryRegion.EUROPE },
  am: { name: 'Armenia', region: CountryRegion.ASIA },
  ao: { name: 'Angola', region: CountryRegion.AFRICA },
  ar: { name: 'Argentina', region: CountryRegion.AMERICA },
  as: { name: 'American Samoa', region: CountryRegion.AMERICA },
  at: { name: 'Austria', region: CountryRegion.EUROPE },
  au: { name: 'Australia', region: CountryRegion.OCEANIA },
  aw: { name: 'Aruba', region: CountryRegion.AMERICA },
  az: { name: 'Azerbaijan', region: CountryRegion.ASIA },
  ba: { name: 'Bosnia and Herzegovina', region: CountryRegion.EUROPE },
  bb: { name: 'Barbados', region: CountryRegion.AMERICA },
  bd: { name: 'Bangladesh', region: CountryRegion.ASIA },
  be: { name: 'Belgium', region: CountryRegion.EUROPE },
  bf: { name: 'Burkina Faso', region: CountryRegion.AFRICA },
  bg: { name: 'Bulgaria', region: CountryRegion.EUROPE },
  bh: { name: 'Bahrain', region: CountryRegion.ASIA },
  bi: { name: 'Burundi', region: CountryRegion.AFRICA },
  bj: { name: 'Benin', region: CountryRegion.AFRICA },
  bm: { name: 'Bermuda', region: CountryRegion.AMERICA },
  bn: { name: 'Brunei', region: CountryRegion.ASIA },
  bo: { name: 'Bolivia', region: CountryRegion.AMERICA },
  bq: { name: 'Caribbean Netherlands', region: CountryRegion.AMERICA },
  br: { name: 'Brazil', region: CountryRegion.AMERICA },
  bs: { name: 'Bahamas', region: CountryRegion.AMERICA },
  bt: { name: 'Bhutan', region: CountryRegion.ASIA },
  bw: { name: 'Botswana', region: CountryRegion.AFRICA },
  by: { name: 'Belarus', region: CountryRegion.EUROPE },
  bz: { name: 'Belize', region: CountryRegion.AMERICA },
  ca: { name: 'Canada', region: CountryRegion.AMERICA },
  cd: { name: 'DR Congo', region: CountryRegion.AFRICA },
  cf: { name: 'Central African Republic', region: CountryRegion.AFRICA },
  cg: { name: 'Republic of the Congo', region: CountryRegion.AFRICA },
  ch: { name: 'Switzerland', region: CountryRegion.EUROPE },
  ci: { name: "Côte d'Ivoire (Ivory Coast)", region: CountryRegion.AFRICA },
  ck: { name: 'Cook Islands', region: CountryRegion.OCEANIA },
  cl: { name: 'Chile', region: CountryRegion.AMERICA },
  cm: { name: 'Cameroon', region: CountryRegion.AFRICA },
  cn: { name: 'China', region: CountryRegion.ASIA },
  co: { name: 'Colombia', region: CountryRegion.AMERICA },
  cr: { name: 'Costa Rica', region: CountryRegion.AMERICA },
  cu: { name: 'Cuba', region: CountryRegion.AMERICA },
  cv: { name: 'Cape Verde', region: CountryRegion.AFRICA },
  cw: { name: 'Curaçao', region: CountryRegion.AMERICA },
  cy: { name: 'Cyprus', region: CountryRegion.EUROPE },
  cz: { name: 'Czechia', region: CountryRegion.EUROPE },
  de: { name: 'Germany', region: CountryRegion.EUROPE },
  dj: { name: 'Djibouti', region: CountryRegion.AFRICA },
  dk: { name: 'Denmark', region: CountryRegion.EUROPE },
  dm: { name: 'Dominica', region: CountryRegion.AMERICA },
  do: { name: 'Dominican Republic', region: CountryRegion.AMERICA },
  dz: { name: 'Algeria', region: CountryRegion.AFRICA },
  ec: { name: 'Ecuador', region: CountryRegion.AMERICA },
  ee: { name: 'Estonia', region: CountryRegion.EUROPE },
  eg: { name: 'Egypt', region: CountryRegion.AFRICA },
  er: { name: 'Eritrea', region: CountryRegion.AFRICA },
  es: { name: 'Spain', region: CountryRegion.EUROPE },
  et: { name: 'Ethiopia', region: CountryRegion.AFRICA },
  fi: { name: 'Finland', region: CountryRegion.EUROPE },
  fj: { name: 'Fiji', region: CountryRegion.OCEANIA },
  fk: { name: 'Falkland Islands', region: CountryRegion.AMERICA },
  fm: { name: 'Micronesia', region: CountryRegion.OCEANIA },
  fo: { name: 'Faroe Islands', region: CountryRegion.EUROPE },
  fr: { name: 'France', region: CountryRegion.EUROPE },
  ga: { name: 'Gabon', region: CountryRegion.AFRICA },
  gb: { name: 'United Kingdom', region: CountryRegion.EUROPE },
  gd: { name: 'Grenada', region: CountryRegion.AMERICA },
  ge: { name: 'Georgia', region: CountryRegion.ASIA },
  gf: { name: 'French Guiana', region: CountryRegion.AMERICA },
  gg: { name: 'Guernsey', region: CountryRegion.EUROPE },
  gh: { name: 'Ghana', region: CountryRegion.AFRICA },
  gi: { name: 'Gibraltar', region: CountryRegion.EUROPE },
  gl: { name: 'Greenland', region: CountryRegion.EUROPE },
  gm: { name: 'Gambia', region: CountryRegion.AFRICA },
  gn: { name: 'Guinea', region: CountryRegion.AFRICA },
  gp: { name: 'Guadeloupe', region: CountryRegion.AMERICA },
  gq: { name: 'Equatorial Guinea', region: CountryRegion.AFRICA },
  gr: { name: 'Greece', region: CountryRegion.EUROPE },
  gs: { name: 'South Georgia', region: CountryRegion.AMERICA },
  gt: { name: 'Guatemala', region: CountryRegion.AMERICA },
  gu: { name: 'Guam', region: CountryRegion.OCEANIA },
  gw: { name: 'Guinea-Bissau', region: CountryRegion.AFRICA },
  gy: { name: 'Guyana', region: CountryRegion.AMERICA },
  hk: { name: 'Hong Kong', region: CountryRegion.ASIA },
  hn: { name: 'Honduras', region: CountryRegion.AMERICA },
  hr: { name: 'Croatia', region: CountryRegion.EUROPE },
  ht: { name: 'Haiti', region: CountryRegion.AMERICA },
  hu: { name: 'Hungary', region: CountryRegion.EUROPE },
  id: { name: 'Indonesia', region: CountryRegion.ASIA },
  ie: { name: 'Ireland', region: CountryRegion.EUROPE },
  il: { name: 'Israel', region: CountryRegion.ASIA },
  in: { name: 'India', region: CountryRegion.ASIA },
  iq: { name: 'Iraq', region: CountryRegion.ASIA },
  ir: { name: 'Iran', region: CountryRegion.ASIA },
  is: { name: 'Iceland', region: CountryRegion.EUROPE },
  it: { name: 'Italy', region: CountryRegion.EUROPE },
  je: { name: 'Jersey', region: CountryRegion.EUROPE },
  jm: { name: 'Jamaica', region: CountryRegion.AMERICA },
  jo: { name: 'Jordan', region: CountryRegion.ASIA },
  jp: { name: 'Japan', region: CountryRegion.ASIA },
  ke: { name: 'Kenya', region: CountryRegion.AFRICA },
  kg: { name: 'Kyrgyzstan', region: CountryRegion.ASIA },
  kh: { name: 'Cambodia', region: CountryRegion.ASIA },
  ki: { name: 'Kiribati', region: CountryRegion.OCEANIA },
  km: { name: 'Comoros', region: CountryRegion.AFRICA },
  kn: { name: 'Saint Kitts and Nevis', region: CountryRegion.AMERICA },
  kp: { name: 'North Korea', region: CountryRegion.ASIA },
  kr: { name: 'South Korea', region: CountryRegion.ASIA },
  kw: { name: 'Kuwait', region: CountryRegion.ASIA },
  ky: { name: 'Cayman Islands', region: CountryRegion.AMERICA },
  kz: { name: 'Kazakhstan', region: CountryRegion.ASIA },
  la: { name: 'Laos', region: CountryRegion.ASIA },
  lb: { name: 'Lebanon', region: CountryRegion.ASIA },
  lc: { name: 'Saint Lucia', region: CountryRegion.AMERICA },
  li: { name: 'Liechtenstein', region: CountryRegion.EUROPE },
  lk: { name: 'Sri Lanka', region: CountryRegion.ASIA },
  lr: { name: 'Liberia', region: CountryRegion.AFRICA },
  ls: { name: 'Lesotho', region: CountryRegion.AFRICA },
  lt: { name: 'Lithuania', region: CountryRegion.EUROPE },
  lu: { name: 'Luxembourg', region: CountryRegion.EUROPE },
  lv: { name: 'Latvia', region: CountryRegion.EUROPE },
  ly: { name: 'Libya', region: CountryRegion.AFRICA },
  ma: { name: 'Morocco', region: CountryRegion.AFRICA },
  mc: { name: 'Monaco', region: CountryRegion.EUROPE },
  md: { name: 'Moldova', region: CountryRegion.EUROPE },
  me: { name: 'Montenegro', region: CountryRegion.EUROPE },
  mf: { name: 'Saint Martin', region: CountryRegion.AMERICA },
  mg: { name: 'Madagascar', region: CountryRegion.AFRICA },
  mh: { name: 'Marshall Islands', region: CountryRegion.OCEANIA },
  mk: { name: 'North Macedonia', region: CountryRegion.EUROPE },
  ml: { name: 'Mali', region: CountryRegion.AFRICA },
  mm: { name: 'Myanmar', region: CountryRegion.ASIA },
  mn: { name: 'Mongolia', region: CountryRegion.ASIA },
  mo: { name: 'Macau', region: CountryRegion.ASIA },
  mp: { name: 'Northern Mariana Islands', region: CountryRegion.OCEANIA },
  mq: { name: 'Martinique', region: CountryRegion.AMERICA },
  mr: { name: 'Mauritania', region: CountryRegion.AFRICA },
  ms: { name: 'Montserrat', region: CountryRegion.AMERICA },
  mt: { name: 'Malta', region: CountryRegion.EUROPE },
  mu: { name: 'Mauritius', region: CountryRegion.AFRICA },
  mv: { name: 'Maldives', region: CountryRegion.ASIA },
  mw: { name: 'Malawi', region: CountryRegion.AFRICA },
  mx: { name: 'Mexico', region: CountryRegion.AMERICA },
  my: { name: 'Malaysia', region: CountryRegion.ASIA },
  mz: { name: 'Mozambique', region: CountryRegion.AFRICA },
  na: { name: 'Namibia', region: CountryRegion.AFRICA },
  nc: { name: 'New Caledonia', region: CountryRegion.OCEANIA },
  ne: { name: 'Niger', region: CountryRegion.AFRICA },
  nf: { name: 'Norfolk Island', region: CountryRegion.OCEANIA },
  ng: { name: 'Nigeria', region: CountryRegion.AFRICA },
  ni: { name: 'Nicaragua', region: CountryRegion.AMERICA },
  nl: { name: 'Netherlands', region: CountryRegion.EUROPE },
  no: { name: 'Norway', region: CountryRegion.EUROPE },
  np: { name: 'Nepal', region: CountryRegion.ASIA },
  nr: { name: 'Nauru', region: CountryRegion.OCEANIA },
  nu: { name: 'Niue', region: CountryRegion.OCEANIA },
  nz: { name: 'New Zealand', region: CountryRegion.OCEANIA },
  om: { name: 'Oman', region: CountryRegion.ASIA },
  pa: { name: 'Panama', region: CountryRegion.AMERICA },
  pe: { name: 'Peru', region: CountryRegion.AMERICA },
  pf: { name: 'French Polynesia', region: CountryRegion.OCEANIA },
  pg: { name: 'Papua New Guinea', region: CountryRegion.OCEANIA },
  ph: { name: 'Philippines', region: CountryRegion.ASIA },
  pk: { name: 'Pakistan', region: CountryRegion.ASIA },
  pl: { name: 'Poland', region: CountryRegion.EUROPE },
  pm: { name: 'Saint Pierre and Miquelon', region: CountryRegion.AMERICA },
  pr: { name: 'Puerto Rico', region: CountryRegion.AMERICA },
  ps: { name: 'Palestine', region: CountryRegion.ASIA },
  pt: { name: 'Portugal', region: CountryRegion.EUROPE },
  pw: { name: 'Palau', region: CountryRegion.OCEANIA },
  py: { name: 'Paraguay', region: CountryRegion.AMERICA },
  qa: { name: 'Qatar', region: CountryRegion.ASIA },
  re: { name: 'Réunion', region: CountryRegion.AFRICA },
  ro: { name: 'Romania', region: CountryRegion.EUROPE },
  rs: { name: 'Serbia', region: CountryRegion.EUROPE },
  ru: { name: 'Russia', region: CountryRegion.EUROPE },
  rw: { name: 'Rwanda', region: CountryRegion.AFRICA },
  sa: { name: 'Saudi Arabia', region: CountryRegion.ASIA },
  sb: { name: 'Solomon Islands', region: CountryRegion.OCEANIA },
  sc: { name: 'Seychelles', region: CountryRegion.AFRICA },
  sd: { name: 'Sudan', region: CountryRegion.AFRICA },
  se: { name: 'Sweden', region: CountryRegion.EUROPE },
  sg: { name: 'Singapore', region: CountryRegion.ASIA },
  si: { name: 'Slovenia', region: CountryRegion.EUROPE },
  sk: { name: 'Slovakia', region: CountryRegion.EUROPE },
  sl: { name: 'Sierra Leone', region: CountryRegion.AFRICA },
  sm: { name: 'San Marino', region: CountryRegion.EUROPE },
  sn: { name: 'Senegal', region: CountryRegion.AFRICA },
  so: { name: 'Somalia', region: CountryRegion.AFRICA },
  sr: { name: 'Suriname', region: CountryRegion.AMERICA },
  ss: { name: 'South Sudan', region: CountryRegion.AFRICA },
  st: { name: 'São Tomé and Príncipe', region: CountryRegion.AFRICA },
  sv: { name: 'El Salvador', region: CountryRegion.AMERICA },
  sx: { name: 'Sint Maarten', region: CountryRegion.AMERICA },
  sy: { name: 'Syria', region: CountryRegion.ASIA },
  sz: { name: 'Eswatini (Swaziland)', region: CountryRegion.AFRICA },
  tc: { name: 'Turks and Caicos Islands', region: CountryRegion.AMERICA },
  td: { name: 'Chad', region: CountryRegion.AFRICA },
  tg: { name: 'Togo', region: CountryRegion.AFRICA },
  th: { name: 'Thailand', region: CountryRegion.ASIA },
  tj: { name: 'Tajikistan', region: CountryRegion.ASIA },
  tk: { name: 'Tokelau', region: CountryRegion.OCEANIA },
  tl: { name: 'Timor-Leste', region: CountryRegion.ASIA },
  tm: { name: 'Turkmenistan', region: CountryRegion.ASIA },
  tn: { name: 'Tunisia', region: CountryRegion.AFRICA },
  to: { name: 'Tonga', region: CountryRegion.OCEANIA },
  tr: { name: 'Turkey', region: CountryRegion.ASIA },
  tt: { name: 'Trinidad and Tobago', region: CountryRegion.AMERICA },
  tv: { name: 'Tuvalu', region: CountryRegion.OCEANIA },
  tw: { name: 'Taiwan', region: CountryRegion.ASIA },
  tz: { name: 'Tanzania', region: CountryRegion.AFRICA },
  ua: { name: 'Ukraine', region: CountryRegion.EUROPE },
  ug: { name: 'Uganda', region: CountryRegion.AFRICA },
  us: { name: 'United States', region: CountryRegion.AMERICA },
  uy: { name: 'Uruguay', region: CountryRegion.AMERICA },
  uz: { name: 'Uzbekistan', region: CountryRegion.ASIA },
  va: { name: 'Vatican City (Holy See)', region: CountryRegion.EUROPE },
  vc: {
    name: 'Saint Vincent and the Grenadines',
    region: CountryRegion.AMERICA,
  },
  ve: { name: 'Venezuela', region: CountryRegion.AMERICA },
  vg: { name: 'British Virgin Islands', region: CountryRegion.AMERICA },
  vi: { name: 'United States Virgin Islands', region: CountryRegion.AMERICA },
  vn: { name: 'Vietnam', region: CountryRegion.ASIA },
  vu: { name: 'Vanuatu', region: CountryRegion.OCEANIA },
  wf: { name: 'Wallis and Futuna', region: CountryRegion.OCEANIA },
  ws: { name: 'Samoa', region: CountryRegion.OCEANIA },
  xk: { name: 'Kosovo', region: CountryRegion.EUROPE },
  ye: { name: 'Yemen', region: CountryRegion.ASIA },
  yt: { name: 'Mayotte', region: CountryRegion.AFRICA },
  za: { name: 'South Africa', region: CountryRegion.AFRICA },
  zm: { name: 'Zambia', region: CountryRegion.AFRICA },
  zw: { name: 'Zimbabwe', region: CountryRegion.AFRICA },
};

export function generateCountries(): Partial<CountryEntity>[] {
  return Object.entries(countriesData).map(([code, data]) => ({
    name: data.name,
    code: code,
    flagAvatarUrl: `https://flagcdn.com/56x42/${code}.webp`,
    flagProductImageUrl: `https://flagcdn.com/192x144/${code}.webp`,
    region: data.region,
  }));
}
