name: Publish DB Package

on:
  push:
    branches:
      - main
    paths:
      - "packages/database/**"
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@nospipi"

      # If you're using a monorepo tool like Turborepo, pnpm, or Yarn workspaces
      - name: Setup pnpm # or npm or yarn as needed
        uses: pnpm/action-setup@v2 # adjust based on your package manager
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install # or npm install or yarn install

      - name: Build package
        run: |
          cd packages/db
          pnpm run build # or npm run build or yarn build

      - name: Publish package
        run: |
          cd packages/db
          pnpm publish --access restricted --no-git-checks # or npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
